name: Deploy & Auto Deploy

on:
  push:
    branches: [main]

jobs:
  dev_deployment_on_merge:
    name: Deploy Dev on (Merge to Main)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      bucket: ${{ steps.export.outputs.bucket }}
      dist: ${{ steps.export.outputs.dist }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure jq is available
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Read TFC Outputs (Dev)
        id: tfc
        uses: hashicorp-forge/terraform-cloud-action/outputs@v1
        with:
          token: ${{ secrets.TF_TOKEN_app_terraform_io }}
          organization: Francis_Global_Solution
          workspace: bookie-dev
          hostname: app.terraform.io
      - name: Export parsed outputs
        id: export
        shell: bash
        run: |
          set -euo pipefail
          JSON='${{ steps.tfc.outputs.workspace-outputs-json }}'
          bucket=$(jq -r '.bucket_name.value // empty' <<<"$JSON")
          dist=$(jq -r '.distribution_id.value // empty' <<<"$JSON")
          [[ -n "$bucket" ]] || { echo "No bucket_name output present"; exit 1; }
          [[ -n "$dist"   ]] || { echo "No distribution_id output present"; exit 1; }
          echo "bucket=$bucket" >> "$GITHUB_OUTPUT"
          echo "dist=$dist"     >> "$GITHUB_OUTPUT"

  deploy_web_dev:
    name: Upload Web Build + Invalidate CF (Dev)
    needs: dev_deployment_on_merge
    if: ${{ needs.dev_deployment_on_merge.result == 'success' && needs.dev_deployment_on_merge.outputs.bucket != '' && needs.dev_deployment_on_merge.outputs.dist != '' }}
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_REGION: us-east-1
      BUCKET_NAME: ${{ needs.dev_deployment_on_merge.outputs.bucket }}
      DIST_ID: ${{ needs.dev_deployment_on_merge.outputs.dist }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps & build
        run: |
          npm set fetch-retries 5
          npm set fetch-retry-maxtimeout 600000
          npm ci --no-audit --fund=false
          npx expo export --platform web --output-dir web-build
          echo "Built files:" && ls -la web-build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Verify outputs & build dir
        shell: bash
        run: |
          set -euo pipefail
          echo "BUCKET_NAME='${BUCKET_NAME}'"
          echo "DIST_ID='${DIST_ID}'"
          [[ -n "${BUCKET_NAME}" ]] || { echo "❌ BUCKET_NAME is empty"; exit 1; }
          [[ -n "${DIST_ID}"     ]] || { echo "❌ DIST_ID is empty"; exit 1; }
          [[ -d web-build        ]] || { echo "❌ web-build directory missing"; ls -la; exit 1; }
      - name: Sync to S3
        run: aws s3 sync web-build "s3://${BUCKET_NAME}" --acl public-read --delete
      - name: Invalidate CF
        run: aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "/*"

  staging_deployment_on_merge:
    name: Deploy Staging on (Merge to Main)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      bucket: ${{ steps.export.outputs.bucket }}
      dist: ${{ steps.export.outputs.dist }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure jq is available
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Read TFC Outputs (Staging)
        id: tfc
        uses: hashicorp-forge/terraform-cloud-action/outputs@v1
        with:
          token: ${{ secrets.TF_TOKEN_app_terraform_io }}
          organization: Francis_Global_Solution
          workspace: bookie-staging
          hostname: app.terraform.io
      - name: Export parsed outputs
        id: export
        shell: bash
        run: |
          set -euo pipefail
          JSON='${{ steps.tfc.outputs.workspace-outputs-json }}'
          bucket=$(jq -r '.bucket_name.value // empty' <<<"$JSON")
          dist=$(jq -r '.distribution_id.value // empty' <<<"$JSON")
          [[ -n "$bucket" ]] || { echo "No bucket_name output present"; exit 1; }
          [[ -n "$dist"   ]] || { echo "No distribution_id output present"; exit 1; }
          echo "bucket=$bucket" >> "$GITHUB_OUTPUT"
          echo "dist=$dist"     >> "$GITHUB_OUTPUT"

  staging_web_deploy:
    name: Upload Web Build + Invalidate CF (Staging)
    needs: staging_deployment_on_merge
    if: ${{ needs.staging_deployment_on_merge.result == 'success' && needs.staging_deployment_on_merge.outputs.bucket != '' && needs.staging_deployment_on_merge.outputs.dist != '' }}
    runs-on: ubuntu-latest
    environment: staging
    env:
      AWS_REGION: us-east-1
      BUCKET_NAME: ${{ needs.staging_deployment_on_merge.outputs.bucket }}
      DIST_ID: ${{ needs.staging_deployment_on_merge.outputs.dist }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps & build
        run: |
          npm set fetch-retries 5
          npm set fetch-retry-maxtimeout 600000
          npm ci --no-audit --fund=false
          npx expo export --platform web --output-dir web-build
          echo "Built files:" && ls -la web-build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Verify outputs & build dir
        shell: bash
        run: |
          set -euo pipefail
          echo "BUCKET_NAME='${BUCKET_NAME}'"
          echo "DIST_ID='${DIST_ID}'"
          [[ -n "${BUCKET_NAME}" ]] || { echo "❌ BUCKET_NAME is empty"; exit 1; }
          [[ -n "${DIST_ID}"     ]] || { echo "❌ DIST_ID is empty"; exit 1; }
          [[ -d web-build        ]] || { echo "❌ web-build directory missing"; ls -la; exit 1; }
      - name: Sync to S3
        run: aws s3 sync web-build "s3://${BUCKET_NAME}" --acl public-read --delete
      - name: Invalidate CF
        run: aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "/*"
